
// eventsData.js
let allEvents = [];

const sampleEvents = [
  {
    id: 1,
    name: "Festival de Verão de Florianópolis",
    description: "O maior festival de música do sul do Brasil com atrações internacionais e nacionais na capital catarinense.",
    location: "Praia da Joaquina, Florianópolis, SC",
    type: "Shows",
    date: "2025-08-15",
    ticketType: "pago",
    price: 220,
    tax: 15,
    rating: "+16",
    image: "/img/Festival de Verão de Florianópolis.png",
    likes: 0,
    purchased: false,
    hasSeats: true,
    totalSeats: 64,
    bookedSeats: [1, 2, 3, 10, 15] 
  },
  {
    id: 2,
    name: "Workshop de Fotografia da Serra Catarinense",
    description: "Aprenda técnicas avançadas de fotografia de natureza com profissionais renomados nas paisagens da serra.",
    location: "Centro Cultural de Lages, SC",
    type: "Workshop",
    date: "2025-07-30",
    ticketType: "pago",
    price: 100,
    tax: 10,
    rating: "Livre",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 3,
    name: "Balada Beira-Mar",
    description: "A balada mais badalada do litoral catarinense com DJs internacionais e vista para o mar.",
    location: "Av. Atlântica, Balneário Camboriú, SC",
    type: "Balada",
    date: "2025-07-26",
    ticketType: "pago",
    price: 90,
    tax: 15,
    rating: "+18",
    image: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 4,
    name: "Rock na Ilha",
    description: "Os maiores nomes do rock nacional em um show histórico na ilha da magia.",
    location: "Centro de Eventos de Florianópolis, SC",
    type: "Shows",
    date: "2025-08-05",
    ticketType: "pago",
    price: 150,
    tax: 12,
    rating: "+14",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
    hasSeats: true,
    totalSeats: 48,
    bookedSeats: [5, 6, 7, 8]
  },
  {
    id: 5,
    name: "Festa Infantil do Vale Europeu",
    description: "Diversão garantida para as crianças com brinquedos temáticos, teatro e oficinas criativas.",
    location: "Parque Vila Germânica, Blumenau, SC",
    type: "Infantil",
    date: "2025-08-10",
    ticketType: "gratuito",
    price: 0,
    tax: 0,
    rating: "Livre",
    image: "https://babies.constancezahn.com/wp-content/uploads/2021/11/captura-de-tela-2021-11-29-as-175731.png",
    likes: 0,
    purchased: false,
  },
  {
    id: 6,
    name: "Imersão Tech SC",
    description: "Aprenda as linguagens mais requisitadas do mercado com especialistas do polo tecnológico catarinense.",
    location: "Universidade Federal de Santa Catarina, Florianópolis, SC",
    type: "Workshop",
    date: "2025-08-18",
    ticketType: "pago",
    price: 180,
    tax: 10,
    rating: "+16",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 7,
    name: "Sunset Lounge",
    description: "Ambiente sofisticado com música eletrônica e drinks exclusivos no litoral norte.",
    location: "Praia Brava, Itajaí, SC",
    type: "Balada",
    date: "2025-08-01",
    ticketType: "pago",
    price: 70,
    tax: 12,
    rating: "+18",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/31/fa/e1/the-atmosfere-in-our.jpg?w=900&h=500&s=1",
    likes: 0,
    purchased: false,
  },
  {
    id: 8,
    name: "Sertanejo do Oeste",
    description: "Os maiores sucessos do sertanejo universitário em uma noite inesquecível no coração do oeste catarinense.",
    location: "Centro de Eventos de Chapecó, SC",
    type: "Shows",
    date: "2025-08-20",
    ticketType: "pago",
    price: 190,
    tax: 15,
    rating: "+16",
    image: "https://focalizando.com.br/sites/default/files/inline-images/cantor-sertanejo-rodolfo.webp",
    likes: 0,
    purchased: false,
    hasSeats: true,
    totalSeats: 32,
    bookedSeats: [1, 2, 3]
  },
  {
    id: 9,
    name: "Beto Carrero Experience",
    description: "Diversão para toda a família com brinquedos exclusivos e atrações especiais no maior parque temático.",
    location: "Beto Carrero World, Penha, SC",
    type: "Infantil",
    date: "2025-08-08",
    ticketType: "pago",
    price: 120,
    tax: 10,
    rating: "Livre",
    image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/36/d9/bc.jpg",
    likes: 0,
    purchased: false,
  },
  {
    id: 10,
    name: "Gourmet Catarina",
    description: "Aprenda a cozinhar pratos típicos da culinária catarinense com chefs renomados.",
    location: "Centro Gastronômico de Blumenau, SC",
    type: "Workshop",
    date: "2025-08-12",
    ticketType: "pago",
    price: 160,
    tax: 10,
    rating: "+12",
    image: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 11,
    name: "Oktoberfest Experience",
    description: "Maior festa alemã das Américas com shows típicos, gastronomia e parque temático.",
    location: "Parque Vila Germânica, Blumenau, SC",
    type: "Shows",
    date: "2025-08-15",
    ticketType: "pago",
    price: 80,
    tax: 8,
    rating: "Livre",
    image: "https://i.ytimg.com/vi/MnCVapaFquY/maxresdefault.jpg",
    likes: 0,
    purchased: false,
  },
  {
    id: 12,
    name: "Workshop de Fotografia de Natureza",
    description: "Técnicas avançadas para capturar as belezas naturais do Parque Nacional Serra do Itajaí.",
    location: "Parque Nacional Serra do Itajaí, SC",
    type: "Workshop",
    date: "2025-07-30",
    ticketType: "pago",
    price: 140,
    tax: 12,
    rating: "Livre",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 13,
    name: "Vibe Urbana",
    description: "A balada mais concorrida da região com pista premium e open bar.",
    location: "Rua das Palmeiras, Joinville, SC",
    type: "Balada",
    date: "2025-07-26",
    ticketType: "pago",
    price: 110,
    tax: 18,
    rating: "+18",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 14,
    name: "Rock no Vale",
    description: "Bandas históricas do rock brasileiro em show exclusivo no vale do Itajaí.",
    location: "Teatro Carlos Gomes, Blumenau, SC",
    type: "Shows",
    date: "2025-08-05",
    ticketType: "pago",
    price: 130,
    tax: 11,
    rating: "+14",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 15,
    name: "Circo da Magia",
    description: "Espectáculo circense interativo com oficinas criativas para crianças.",
    location: "Parque Ramiro Ruediger, Joinville, SC",
    type: "Infantil",
    date: "2025-08-10",
    ticketType: "gratuito",
    price: 0,
    tax: 0,
    rating: "Livre",
    image: "https://i.ytimg.com/vi/TyQMUg_Xg4U/maxresdefault.jpg",
    likes: 0,
    purchased: false,
  },
  {
    id: 16,
    name: "Startup Weekend",
    description: "Imersão em empreendedorismo tecnológico com mentores do ecossistema inovador catarinense.",
    location: "Acate, Florianópolis, SC",
    type: "Workshop",
    date: "2025-08-18",
    ticketType: "pago",
    price: 210,
    tax: 15,
    rating: "+16",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=600&w=800",
    likes: 0,
    purchased: false,
  },
  {
    id: 17,
    name: "Beach Club",
    description: "Experiência premium com piscina infinita e DJs internacionais na capital.",
    location: "Praia Mole, Florianópolis, SC",
    type: "Balada",
    date: "2025-08-01",
    ticketType: "pago",
    price: 150,
    tax: 20,
    rating: "+18",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSe9feC5JkUqw6gCVBB--9xFiGbD40GmxNQw&s",
    likes: 0,
    purchased: false,
  },
  {
    id: 18,
    name: "Festa do Colono",
    description: "Celebração da cultura sertaneja com shows regionais e gastronomia típica.",
    location: "Parque de Exposições de Chapecó, SC",
    type: "Shows",
    date: "2025-08-20",
    ticketType: "pago",
    price: 60,
    tax: 5,
    rating: "Livre",
    image: "https://www.sideropolis.sc.gov.br/uploads/sites/447/2023/07/DSC_1722-1024x678.jpg",
    likes: 0,
    purchased: false,
    hasSeats: true,
    totalSeats: 56,
    bookedSeats: [10, 11, 12]
  },
  {
    id: 19,
    name: "Mundo das Crianças",
    description: "Parque temático com brinquedos educativos e oficinas de arte.",
    location: "Shopping Neumarkt, Blumenau, SC",
    type: "Infantil",
    date: "2025-08-08",
    ticketType: "pago",
    price: 40,
    tax: 4,
    rating: "Livre",
    image: "https://jundiai.sp.gov.br/noticias/wp-content/uploads/sites/32/2025/07/mundo-das-criancas-1-840x473-1.jpg",
    likes: 0,
    purchased: false,
  },
  {
    id: 20,
    name: "Mariscos da Ilha",
    description: "Oficina de culinária especializada em frutos do mar com chefs locais.",
    location: "Mercado Público, Florianópolis, SC",
    type: "Workshop",
    date: "2025-08-12",
    ticketType: "pago",
    price: 170,
    tax: 14,
    rating: "+12",
    image: "https://i0.wp.com/blog.duogourmet.com.br/wp-content/uploads/2025/04/Restaurante-de-Frutos-do-Mar-em-Florianopolis.jpg?fit=800%2C533&ssl=1",
    likes: 0,
    purchased: false,
  },
  {
    id: 21,
    name: "Rodeio Crioulo Internacional",
    description: "Maior evento de tradição gaúcha do estado com competições e shows.",
    location: "Parque de Exposições de Lages, SC",
    type: "Shows",
    date: "2025-08-22",
    ticketType: "pago",
    price: 75,
    tax: 7,
    rating: "Livre",
    image: "https://s2-g1.glbimg.com/HKElSxJMd9NQ2_WhdYO3UiiGFYw=/0x0:650x434/984x0/smart/filters:strip_icc()/s.glbimg.com/jo/g1/f/original/2013/11/08/vacaria.jpg",
    likes: 0,
    purchased: false,
  },
  {
    id: 22,
    name: "Festival de Dança de Joinville",
    description: "Espetáculos de dança clássica e contemporânea com companhias internacionais.",
    location: "Centreventos Cau Hansen, Joinville, SC",
    type: "Shows",
    date: "2025-08-25",
    ticketType: "pago",
    price: 95,
    tax: 9,
    rating: "Livre",
    image: "https://www.dancaempauta.com.br/wp-content/uploads/2017/06/aba_festival-danca-joinville.jpg",
    likes: 1,
    purchased: false,
    hasSeats: true,
    totalSeats: 64,
    bookedSeats: [1, 2, 3, 4, 5]
  },
  {
    id: 23,
    name: "Caminhos do Sertão",
    description: "Show de forró pé-de-serra com bandas consagradas do nordeste.",
    location: "Centro de Eventos de Itajaí, SC",
    type: "Shows",
    date: "2025-08-28",
    ticketType: "pago",
    price: 65,
    tax: 6,
    rating: "+14",
    image: "https://www.pragmatismopolitico.com.br/wp-content/uploads/2018/01/forro-pe-de-serra-o-ritmo-do-povo.jpg",
    likes: 0,
    purchased: false,
  }
];

function initializeEvents() {
  allEvents = JSON.parse(localStorage.getItem("events")) || sampleEvents;
  localStorage.setItem('events', JSON.stringify(allEvents));
}

